const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    join(__dirname, '../../libs/**/!(*.stories|*.spec).{ts,html}'),
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed-variant": "#004c6e",
        "primary-container": "#0ea5e9",
        "inverse-primary": "#89ceff",
        "surface-dim": "#d8dadc",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-high": "#e6e8ea",
        "secondary-container": "#d0e1fb",
        "surface": "#f7f9fb",
        "on-surface-variant": "#3e4850",
        "outline-variant": "#bec8d2",
        "on-secondary-container": "#54647a",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#003751",
        "primary-fixed": "#c9e6ff",
        "primary": "#006591",
        "secondary": "#505f76",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-container": "#00b17b",
        "tertiary": "#006c49",
        "surface-tint": "#006591",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#003b26",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-variant": "#e0e3e5",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#89ceff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#6ffbbe",
        "outline": "#6e7881",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "on-tertiary-fixed": "#002113",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001e2f"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-desktop": "32px",
        "stack-md": "16px",
        "sidebar-width": "280px",
        "gutter": "24px",
        "stack-lg": "24px",
        "base": "4px",
        "stack-sm": "8px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "sans": ["Hanken Grotesk", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};
